apiVersion: v1
kind: Pod
metadata:
  name: app-test-pod
  labels:
    app: custom-app
spec:
  containers:
  - name: app
    image: custom-app:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
    env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: LOG_LEVEL
    - name: APP_PORT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_PORT
    - name: WELCOME_MESSAGE
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: WELCOME_MESSAGE
    volumeMounts:
    - name: logs-volume
      mountPath: /app/logs
  volumes:
  - name: logs-volume
    emptyDir: {}
